spring:
  datasource:
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: caffeine
    cache-names:
      - users
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s